source 'http://rubygems.org'


gem 'cfndsl', '~> 0.16'
gem 'thor'
gem 'highline', '>=1.7.10', '<1.8'
gem 'aws-sdk-core', '~> 3', '<4'
gem 'aws-sdk-s3', '~> 1', '<2'
gem 'aws-sdk-ec2', '~> 1', '<2'
gem 'aws-sdk-cloudformation', '~> 1', '<2'
gem 'rubyzip', '>= 1.2.1'
gem 'git', '~> 1.4', '<2'
gem 'netaddr', '~> 1.5', '>= 1.5.1'
gem 'rspec'
gem 'octokit', '~> 4.0'