source 'https://rubygems.org'


gem 'cfndsl', '>1', '<2'
gem 'thor'
gem 'highline', '>=1.7.10', '<1.8'
gem 'aws-sdk-core', '~> 3', '<4'
gem 'aws-sdk-s3', '~> 1', '<2'
gem 'aws-sdk-ec2', '~> 1', '<2'
gem 'aws-sdk-cloudformation', '~> 1', '<2'
gem 'rubyzip', '>= 2.0.0', '<3'
gem 'git', '~> 1.4', '<2'
gem 'rspec'
gem 'octokit', '~> 4.0'
gem 'duplicate','~> 1.1'